//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysFileReplacer.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SysFileReplacer.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Application is already runinng. This instance will be closed..
        /// </summary>
        internal static string ApplicationIsAlreadyRuninng {
            get {
                return ResourceManager.GetString("ApplicationIsAlreadyRuninng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Backup directory {0} already created..
        /// </summary>
        internal static string BackupDirectoryAlreadyCreated {
            get {
                return ResourceManager.GetString("BackupDirectoryAlreadyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Backup for file {0} created..
        /// </summary>
        internal static string BackupForFileCreated {
            get {
                return ResourceManager.GetString("BackupForFileCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Backup for file {0} is already exist..
        /// </summary>
        internal static string BackupForFileIsAlreadyExist {
            get {
                return ResourceManager.GetString("BackupForFileIsAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot create backup for file: {0}.
        /// </summary>
        internal static string CannotCreateBackupForFile {
            get {
                return ResourceManager.GetString("CannotCreateBackupForFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot disable windows file protection for file {0}.
        /// </summary>
        internal static string CannotDisableWindowsFileProtectionForFile {
            get {
                return ResourceManager.GetString("CannotDisableWindowsFileProtectionForFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot get ownership for file {0}.
        /// </summary>
        internal static string CannotGetOwnershipForFile {
            get {
                return ResourceManager.GetString("CannotGetOwnershipForFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Created backup directory: {0}.
        /// </summary>
        internal static string CreatedBackupDirectory {
            get {
                return ResourceManager.GetString("CreatedBackupDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Creating backup for files....
        /// </summary>
        internal static string CreatingBackupForFiles {
            get {
                return ResourceManager.GetString("CreatingBackupForFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current operation system is not supported..
        /// </summary>
        internal static string CurrentOperationSystemIsNotSupported {
            get {
                return ResourceManager.GetString("CurrentOperationSystemIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File {0} successfully replaced..
        /// </summary>
        internal static string FileSuccessfullyReplaced {
            get {
                return ResourceManager.GetString("FileSuccessfullyReplaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ownership succesfully changed for file {0}.
        /// </summary>
        internal static string OwnershipSuccesfullyChangedForFile {
            get {
                return ResourceManager.GetString("OwnershipSuccesfullyChangedForFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Press any key to continue..
        /// </summary>
        internal static string PressAnyKeyToContinue {
            get {
                return ResourceManager.GetString("PressAnyKeyToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Replace file {0} action cannot be completed because file is used by another process..
        /// </summary>
        internal static string ReplaceFileActionCannotBeCompletedBecauseFileIsUsedByAnotherProcess {
            get {
                return ResourceManager.GetString("ReplaceFileActionCannotBeCompletedBecauseFileIsUsedByAnotherProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Replacing Files....
        /// </summary>
        internal static string ReplacingFiles {
            get {
                return ResourceManager.GetString("ReplacingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Windows file protection successfully disabled for file {0}.
        /// </summary>
        internal static string WindowsFileProtectionSuccessfullyDisabledForFile {
            get {
                return ResourceManager.GetString("WindowsFileProtectionSuccessfullyDisabledForFile", resourceCulture);
            }
        }
    }
}
